<a href="https://colab.research.google.com/github/fmassini/DataScienceCoderhouse/blob/main/Anteriores/Datasets_Massini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd /content/gdrive/MyDrive/Files
import pandas as pd

Mounted at /content/gdrive
/content/gdrive/MyDrive/Files

DATASET 1

El conjunto de datos proviene de FIFA 23 de EA Sports. Contiene información sobre jugadores de fútbol, como nombre, edad, nacionalidad, posición, calificaciones y contratos durante la temporada de fútbol 2022/2023. Los datos se recopilaron mediante seguimiento en vivo, investigación y pruebas realizadas por FIFA, funcionarios de la liga y analistas que cubrieron cada partido.

En el fútbol profesional, los jugadores a menudo se evalúan en función de una variedad de atributos, como su velocidad, habilidad y calificación general. Sin embargo, no está claro si existen diferencias en las calificaciones de los jugadores según su nacionalidad, edad, u otro atributo. Esta investigación tiene como objetivo explorar la relación entre las variables de un jugador de fútbol y sus calificaciones utilizando datos del conjunto de datos de jugadores de FIFA 23. Se podría haber predicho el campeón del mundo con esta información?

https://www.kaggle.com/datasets/babatundezenith/fifa-archive?resource=download

Algunas variables de interés:

In [ ]:
FIFA=pd.read_excel('Fifa_23_Players_Data.xlsx',sheet_name='Hoja2')
FIFA

,COLUMNA,DESCRIPCIÓN,EJEMPLO 1,EJEMPLO 2
0,Full Name,NOMBRE DEL JUGADOR,Lionel Messi,Karim Benzema
1,Overall,VALORACIÓN ACTUAL,91,91
2,Potential,VALORACIÓN POTENCIAL A FUTURO,91,91
3,Value(in Euro),VALOR DEL JUGADOR,54000000,64000000
4,Positions Played,POSICIÓN,RW,"CF,ST"
5,Nationality,NACIONALIDAD,Argentina,France
6,Age,EDAD,35,34
7,Height(in cm),ALTURA,169,185
8,Weight(in kg),PESO,67,81
9,TotalStats,TOTAL ESTADÍSTICAS,2190,2147
10,BaseStats,ESTADÍSTICAS BASE,452,455
11,Club Name,CLUB,Paris Saint-Germain,Real Madrid CF
12,Preferred Foot,PIE PREFERIDO,Left,Right
13,National Team Name,SELECCIÓN PERTENECIENTE,Argentina,France

DATASET:

In [ ]:
FIFA=pd.read_excel('Fifa_23_Players_Data.xlsx',sheet_name='Hoja1')
FIFA

,Known As,Full Name,Overall,Potential,Value(in Euro),Positions Played,Best Position,Nationality,Image Link,Age,...,LM Rating,CM Rating,RM Rating,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating
0,L. Messi,Lionel Messi,91,91,54000000,RW,CAM,Argentina,https://cdn.sofifa.net/players/158/023/23_60.png,35,...,91,88,91,67,66,67,62,53,62,22
1,K. Benzema,Karim Benzema,91,91,64000000,"CF,ST",CF,France,https://cdn.sofifa.net/players/165/153/23_60.png,34,...,89,84,89,67,67,67,63,58,63,21
2,R. Lewandowski,Robert Lewandowski,91,91,84000000,ST,ST,Poland,https://cdn.sofifa.net/players/188/545/23_60.png,33,...,86,83,86,67,69,67,64,63,64,22
3,K. De Bruyne,Kevin De Bruyne,91,91,107500000,"CM,CAM",CM,Belgium,https://cdn.sofifa.net/players/192/985/23_60.png,31,...,91,91,91,82,82,82,78,72,78,24
4,K. MbappÃ©,Kylian MbappÃ©,91,95,190500000,"ST,LW",ST,France,https://cdn.sofifa.net/players/231/747/23_60.png,23,...,92,84,92,70,66,70,66,57,66,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17524,D. Collins,Darren Collins,47,56,110000,"ST,RM",CAM,Republic of Ireland,https://cdn.sofifa.net/players/243/725/23_60.png,21,...,50,44,50,41,38,41,40,36,40,15
17525,Yang Dejiang,Dejiang Yang,47,57,90000,CDM,CDM,China PR,https://cdn.sofifa.net/players/261/933/23_60.png,17,...,45,45,45,47,48,47,49,49,49,15
17526,L. Mullan,Liam Mullan,47,67,130000,CM,RM,Northern Ireland,https://cdn.sofifa.net/players/267/823/23_60.png,18,...,52,49,52,46,44,46,46,42,46,17
17527,D. McCallion,DaithÃ­ McCallion,47,61,100000,CB,CB,Republic of Ireland,https://cdn.sofifa.net/players/267/824/23_60.png,17,...,33,33,33,44,42,44,47,49,47,15
17528,N. Rabha,Nabin Rabha,47,50,60000,LB,LB,India,https://cdn.sofifa.net/players/261/424/23_60.png,25,...,44,40,44,46,43,46,47,47,47,19

DATASET 2

¿Es posible predecir si las personas recibieron las vacunas contra la gripe H1N1 y la gripe estacional utilizando la información que compartieron sobre sus antecedentes, opiniones y comportamientos de salud?

Una vacuna para el virus de la gripe H1N1 estuvo disponible para el público a partir de octubre de 2009. A finales de 2009 y principios de 2010, Estados Unidos llevó a cabo la Encuesta Nacional de Gripe H1N1 de 2009. Esta encuesta telefónica preguntó a los encuestados si habían recibido las vacunas contra la gripe H1N1 y la gripe estacional, junto con preguntas sobre ellos mismos. Estas preguntas adicionales abarcaban su situación social, económica y demográfica, opiniones sobre los riesgos de enfermedad y la efectividad de las vacunas, y comportamientos para mitigar la transmisión. Un mejor entendimiento de cómo estas características se relacionan con los patrones personales de vacunación puede proporcionar orientación para futuros esfuerzos de salud pública.

https://www.drivendata.org/competitions/66/flu-shot-learning/page/211/

Algunas variables de interés:

In [ ]:
H1N1=pd.read_excel('Predict H1N1 and Seasonal Flu Vaccines.xlsx',sheet_name='Hoja2')
H1N1

,COLUMNA,DESCRIPCIÓN,EJEMPLO 1,EJEMPLO 2
0,h1n1_concern,Nivel de preocupación sobre la H1N1,1,3
1,h1n1_knowledge,Nivel de conocimiento sobre la H1N1,0,2
2,behavioral_antiviral_meds,Si ha tomado medicamentos antivirales,0,0
3,behavioral_avoidance,Si ha tratado de evitar contacto con personas ...,1,1
4,behavioral_face_mask,Si usa mascarilla,0,0
5,behavioral_wash_hands,Si es de lavarse las manos seguido,1,1
6,behavioral_large_gatherings,Si ha tratado de evitar reuniones,0,0
7,behavioral_outside_home,Si tiene poco contacto con personas fuera de s...,0,1
8,behavioral_touch_face,Si evita tocarse el rostro,1,1
9,doctor_recc_h1n1,La vacuna H1N1 fue recomendada por su médico,1,0
10,doctor_recc_seasonal,La vacuna gripe fue recomendada por su médico,0,0
11,chronic_med_condition,Es una persona con comorbilidades,1,0
12,health_worker,Trabaja en la salud,0,0
13,health_insurance,Tiene seguro de salud,1,1
14,opinion_h1n1_vacc_effective,Efectividad que cree que tiene la vacuna de H1N1,5,5
15,opinion_h1n1_risk,Riesgo que representa contraer H1N1,2,4
16,opinion_h1n1_sick_from_vacc,Preocupación por enfermarse de H1N1 al tomar l...,1,4
17,opinion_seas_vacc_effective,Efectividad que cree que tiene la vacuna de gripe,4,4
18,opinion_seas_risk,Riesgo que representa contraer gripe,2,2
19,opinion_seas_sick_from_vacc,Preocupación por enfermarse de gripe al tomar ...,1,4
20,age_group,Edad,45 - 54 Years,35 - 44 Years
21,education,Educación,Some College,12 Years
22,race,Raza,White,White
23,sex,Sexo,Female,Male
24,income_poverty,Economía,"<= $75,000, Above Poverty",Below Poverty
25,marital_status,Estado civil,Married,Not Married
26,rent_or_own,Vivienda propia o alquilada,Own,Rent
27,employment_status,Trabaja?,Employed,Employed
28,household_adults,Con cuantos adultos más vive?,2,0
29,household_children,Con cuantos niños vive?,0,0

DATASET:

In [ ]:
H1N1=pd.read_excel('Predict H1N1 and Seasonal Flu Vaccines.xlsx',sheet_name='Hoja1')
H1N1

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53410,53410,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,dqpwygqj,"MSA, Principle City",1.0,1.0,NaN,NaN
53411,53411,3.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,...,Below Poverty,Married,Rent,Employed,qufhixun,Non-MSA,1.0,3.0,fcxhlnwr,vlluhbov
53412,53412,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,qufhixun,"MSA, Not Principle City",1.0,0.0,NaN,NaN
53413,53413,3.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,bhuqouqj,"MSA, Not Principle City",1.0,0.0,NaN,NaN
53414,53414,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,NaN,Not Married,Rent,Employed,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,xtkaffoo

DATASET 3

El siguiente dataset contiene información sobre las piezas con su respectivo código (referencia) necesarias para construir distintas versiones de un producto en específico.
La mercadería viene en cajones llamados "bases" dentro de contenedores. A su vez, cada caja en estas bases tiene dentro un número determinado de piezas. En resumen, la pieza viene en cajas, las cuales vienen en bases, las cuales a su vez vienen en contenedores.

Lo interesante a ver en este estudio, es definir si existe un patrón en los contenedores y bases en los cuales viene la mercadería, y si ese patrón además se extiende a las 5 versiones existentes (cada fila además aclara a que versión del producto pertenece la pieza, hay piezas comunes a todos y otras que no lo son).
Es de particular interés encontrar si existe una combinación de contenedores que, si se los trae primero, esto permita contar con todas las piezas para armar el producto lo antes posible.

Una vez traidos los contenedores, las piezas deberán separarse en clases. Sabiendo el volumen y peso de las mismas, también es de interés determinar que clase es más voluminosa y a cuantas posiciones en una estantería equivaldría. Esto difiere mucho versión a versión?

Fuente: https://docs.google.com/spreadsheets/d/1ouprDoTPf1Ua6wY1ZZ1FbcAgWx1ejaNl/edit?usp=drivesdk&ouid=111044325679429769254&rtpof=true&sd=true

Algunas variables de interés:

In [ ]:
DSNX=pd.read_excel('DS producto.xlsx',sheet_name='Hoja2')
DSNX

,COLUMNA,DESCRIPCIÓN,EJEMPLO 1,EJEMPLO 2
0,CLASE,Sector en el cual se ensambla esta pieza,F1,A
1,VERSION,Versión del producto al cual pertenece esta pieza,M42,A42
2,CONTENEDOR,Contenedor en el cual viene esta pieza,CMAU4908460,MRSU3285393
3,BASE,Base en la cual viene esta pieza,AF0001,MP001
4,TIPO BASE,Tipo de base,IRON FRAME,IRON FRAME
5,LARGO BASE,Largo de la base en mm,2110,2250
6,ANCHO BASE,Ancho de la base en mm,600,1700
7,ALTURA BASE,Altura de la base en mm,1200,1050
8,PESO BASE,Peso de la base en kg,205,861.0
9,CAJA,Caja en la cual viene esta pieza,AF0001,MC0072
10,TIPO CAJA,Tipo de caja,IRON FRAME,CARTON
11,LARGO CAJA,Largo de la caja en mm,1700,800
12,ANCHO CAJA,Ancho de la caja en mm,100,500
13,ALTURA CAJA,Altura de la caja en mm,130,530
14,PESO CAJA,Peso de la caja en kg,153.92,13.85
15,REFERENCIA,Código de esta pieza,2804110-BU01,6900006P201D
16,UNID/CAJA,Cantidad de esta pieza que viene en la caja,16,16

DATASET:

In [ ]:
DSNX=pd.read_excel('DS producto.xlsx',sheet_name='Hoja1')
DSNX

,CLASE,VERSION,CONTENEDOR,BASE,TIPO BASE,LARGO BASE,ANCHO BASE,ALTURA BASE,PESO BASE,CAJA,TIPO CAJA,LARGO CAJA,ANCHO CAJA,ALTURA CAJA,PESO CAJA,REFERENCIA,UNID/CAJA
0,F1,M42,CMAU4908460,AF0001,IRON FRAME,2110,600,1200,205.0,AF0001,IRON FRAME,1700,100,130,153.92,2804110-BU01,16
1,F1,M42,CMAU4908460,AF0002,IRON FRAME,2110,600,1200,205.0,AF0002,IRON FRAME,1700,100,130,153.92,2804110-BU01,16
2,F1,M42,CMAU4908460,AF0003,IRON FRAME,2110,600,1200,205.0,AF0003,IRON FRAME,1700,100,130,153.92,2804110-BU01,16
3,F1,M42,CMAU4908460,AF0004,IRON FRAME,2110,600,1200,205.0,AF0004,IRON FRAME,1700,100,130,153.92,2804110-BU01,16
4,F1,M42,CMAU4908460,AF0005,IRON FRAME,2110,600,1200,205.0,AF0005,IRON FRAME,1700,100,130,153.92,2804110-BU01,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23599,A,A42,MRSU3285393,MP001,IRON FRAME,2250,1700,1050,861.0,MC0074,CARTON,550,460,360,6.81,7100004P201E,96
23600,A,A42,MRSU3285393,MP001,IRON FRAME,2250,1700,1050,861.0,MC0074,CARTON,550,460,360,6.81,7100005P201E,96
23601,A,A42,MRSU3285393,MP001,IRON FRAME,2250,1700,1050,861.0,MC0074,CARTON,550,460,360,6.81,7200004P201E,96
23602,A,A42,MRSU3285393,MP001,IRON FRAME,2250,1700,1050,861.0,MC0074,CARTON,550,460,360,6.81,7200005P201E,96
23603,A,A42,MRSU3285393,MP001,IRON FRAME,2250,1700,1050,861.0,MC0075,CARTON,530,280,260,15.97,7200006P201E,384